### ISSUE TITLE
GPU in colab

### ISSUE THREAD

**Issue by mrmoonshine24** [michhar/maskrcnn-custom#12]
Hi,

thanks for your very clear tutorial. However, when i want to run this within colab, the cpu is only working and will get a notification that the gpu is not being used. Any idea where the issue could be in?

Thanks

**Comment by mrmoonshine24** [comment]
> Hi,
> 
> thanks for your very clear tutorial. However, when i want to run this within colab, the cpu is only working and will get a notification that the gpu is not being used. Any idea where the issue could be in?
> 
> Thanks

Found the problem. Using different requirements.txt solved the issue for me. 
numpy
scipy
Pillow
cython
matplotlib
scikit-image==0.16.2
tensorflow==1.15.0
keras==2.1.6
opencv-python
h5py==2.10
imgaug
IPython[all]

thanks!

**Comment by michhar** [comment]
Thanks for the update!!
