### ISSUE TITLE
How to configure for variable image dimension ?

### ISSUE THREAD

**Issue by nikhilparmar** [michhar/maskrcnn-custom#5]
What changes do I need to make so that I can train with variable image dimensions ? What strategy do I need to follow to solve this issue ?

Apologies for such questions,
Thanks

**Comment by michhar** [comment]
Hi,
Thanks for the good question.  I have not tried with variable image sizes.  Could you provide the error you see when you try?  I will try to help if I can.

You may wish to look in the `config.py` at:
- https://github.com/michhar/maskrcnn-custom/blob/aad9724db054069fa49bb11a2775f550bd4034d9/mrcnn/config.py#L211
- https://github.com/michhar/maskrcnn-custom/blob/aad9724db054069fa49bb11a2775f550bd4034d9/custom.py#L95
- 
Thanks.

**Comment by nikhilparmar** [comment]
> Hi,
> Thanks for the good question. I have not tried with variable image sizes. Could you provide the error you see when you try? I will try to help if I can.
> 
> You may wish to look in the `config.py` at:
> 
> * https://github.com/michhar/maskrcnn-custom/blob/aad9724db054069fa49bb11a2775f550bd4034d9/mrcnn/config.py#L211
> * https://github.com/michhar/maskrcnn-custom/blob/aad9724db054069fa49bb11a2775f550bd4034d9/custom.py#L95
> 
> Thanks.

Okay nice. So if at line no. 95, if I make it 1024x1024, then all the images will be resized to it right ? Also will it make necessary changes to the annotation coordinates as per the mentioned dimensions ?

Thanks

**Comment by michhar** [comment]
@nikhilparmar I'm afraid I'm not sure of the downstream effects as I haven't tried, but did this help you solve the variable image dimension issue?  Thanks!
