### ISSUE TITLE
Convert h5 to pb

### ISSUE THREAD

**Issue by sctrueew** [michhar/maskrcnn-custom#7]
Hello,

I have trained a custom model and I used keras_to_tensorflow.py to convert it. But I get an error. Have you ever converted it and use it in OpencvDnn?

Thanks

**Comment by michhar** [comment]
Hello @zpmmehrdad.  Thanks for trying out the repo.  I have not tried yet to convert to TF with this Keras MaskRCNN model, but here is some guidance.  First, I’d ensure the operations are all supported in my conversion tool.  Second, I would ensure using all of the same Python package versions.  Third thing I usually check is that I specify the right number of classes in the case it’s a dimension error.  But just general guidance without seeing your code or error.  Best and hopefully this is of some help.
