### ISSUE TITLE
Testing the trained model and comparing with ground truth.

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [michhar/maskrcnn-custom#9]
I have obtained a trained model in logs at 40 epochs. I have the annotations json of my test set. How can I test this resultant model on each image and compare it with the true annotations?

**Comment by michhar** [comment]
Great question.  An evaluation method for getting mAP etc. has not been built yet, but is on my backlog for this project.  I only have the image and video inferencing code.  I work on this in my spare time so not sure when I’ll have formal evaluation, but I plan to create in the near future.  Glad to hear the request so thank you.

**Comment by mansi-aggarwal-2504** [comment]
I didn’t necessarily mean evaluating via metric. 
But right now, I have a model trained on my dataset and validated using val dataset, saved in my logs.
How do I use to to get annotations/bounding box/polygons on the test set, first? 
Maybe I can visualise the prediction and actual annotation for a certain image to check how it’s performing later on

**Comment by michhar** [comment]
Oh got it.  I don’t have a function for bounding boxes on images, just video.  For images, it will be a “splash of color” or the area inside a bounding box shows color and the rest of the image will be grayscale.  You could adapt the bounding box drawing function for images if you like.

**Comment by mansi-aggarwal-2504** [comment]
Thank you, will try this!
